import { SITE_CONFIG } from "@/lib/constants/config";
import sitemap from "@/app/sitemap";
import { countSummary, fail, ok, warn } from "./helpers";
import { buildExpectedSitemapPaths, buildKnownRoutes, normalizePath } from "./known-routes";
import type { CheckResult, HealthSection } from "./types";

export function runSitemapChecks(): HealthSection {
  const checks: CheckResult[] = [];
  const entries = sitemap();
  const urls = entries.map((entry) => entry.url);

  checks.push(
    ok("sitemap.total", "Total URLs", `${urls.length} URL(s) generated by the sitemap route`)
  );

  const duplicates = urls.filter((url, index) => urls.indexOf(url) !== index);
  const unique = Array.from(new Set(duplicates));
  if (unique.length === 0) {
    checks.push(ok("sitemap.duplicates", "Duplicate URLs", "No duplicate URLs in the sitemap."));
  } else {
    checks.push(
      fail(
        "sitemap.duplicates",
        "Duplicate URLs",
        `${unique.length} duplicate URL(s). ${countSummary(unique)}`
      )
    );
  }

  const expectedPaths = buildExpectedSitemapPaths();
  const sitemapPaths = new Set(urls.map((url) => normalizePath(url)));
  const missingPaths = expectedPaths.filter((path) => {
    const normalized = normalizePath(path);
    return normalized !== "" && !sitemapPaths.has(normalized);
  });

  if (missingPaths.length === 0) {
    checks.push(
      ok("sitemap.missing", "Missing URLs", "Every known page is present in the sitemap.")
    );
  } else {
    checks.push(
      fail(
        "sitemap.missing",
        "Missing URLs",
        `${missingPaths.length} known page(s) missing from the sitemap. ${countSummary(missingPaths)}`
      )
    );
  }

  const knownRoutes = buildKnownRoutes();
  const invalidRoutes: string[] = [];
  for (const url of urls) {
    if (!url.startsWith(SITE_CONFIG.url)) {
      invalidRoutes.push(`${url} (outside site base URL)`);
      continue;
    }
    const relative = normalizePath(url);
    if (relative !== "" && !knownRoutes.has(relative)) {
      invalidRoutes.push(`${url} (unrecognized route)`);
    }
  }

  if (invalidRoutes.length === 0) {
    checks.push(ok("sitemap.invalid", "Invalid routes", "All sitemap URLs map to known routes."));
  } else {
    checks.push(
      warn(
        "sitemap.invalid",
        "Invalid routes",
        `${invalidRoutes.length} sitemap URL(s) that do not map to a known route. ${countSummary(invalidRoutes)}`
      )
    );
  }

  return {
    id: "sitemap",
    title: "Sitemap",
    description: "Validates the generated sitemap.xml against the known route registry.",
    checks,
  };
}
